export const roomList = [
	{
		type: 'Phòng Superior Có Giường Cỡ King',
		guests: '2 người lớn',
		price: 'VND 940.680',
		originalPrice: 'VND 2.400.000',
		discount: 'Tiết kiệm 61%',
		options: [
			'Bao bữa sáng tự chọn',
			'Không cần thẻ tín dụng',
			'Miễn phí huỷ trước kỳ nghỉ',
			'Không cần thanh toán trước - thanh toán tại chỗ nghỉ',
			'Genius - Có thể có giảm giá',
			'Chỉ còn 5 phòng trống tại trang của chúng tôi',
		],
		select: true,
	},
	{
		type: 'Phòng Superior 2 Giường Đơn',
		guests: '2 giường đơn',
		price: 'VND 940.680',
		originalPrice: 'VND 2.400.000',
		discount: 'Tiết kiệm 61%',
		options: [
			'Bao bữa sáng tự chọn',
			'Không cần thẻ tín dụng',
			'Miễn phí huỷ trước kỳ nghỉ',
			'Không cần thanh toán trước - thanh toán tại chỗ nghỉ',
			'Genius - Có thể có giảm giá',
			'Chỉ còn 5 phòng trống tại trang của chúng tôi',
		],
		select: true,
	},
	{
		type: 'Phòng Deluxe có Giường cỡ King Nhìn ra Khu vườn',
		guests: '2 người lớn',
		price: 'VND 1.063.530',
		originalPrice: 'VND 2.700.000',
		discount: 'Tiết kiệm 61%',
		options: [
			'Bao bữa sáng tự chọn',
			'Không cần thẻ tín dụng',
			'Miễn phí huỷ trước kỳ nghỉ',
			'Không cần thanh toán trước - thanh toán tại chỗ nghỉ',
			'Genius - Có thể có giảm giá',
			'Chỉ còn 4 phòng trống tại trang của chúng tôi',
		],
		select: true,
	},
	{
		type: 'Phòng Deluxe 2 Giường Đơn Nhìn Ra Vườn',
		guests: '2 giường đơn',
		price: 'VND 1.063.530',
		originalPrice: 'VND 2.700.000',
		discount: 'Tiết kiệm 61%',
		options: [
			'Bao bữa sáng tự chọn',
			'Không cần thẻ tín dụng',
			'Miễn phí huỷ trước kỳ nghỉ',
			'Không cần thanh toán trước - thanh toán tại chỗ nghỉ',
			'Genius - Có thể có giảm giá',
			'Chỉ còn 4 phòng trống tại trang của chúng tôi',
		],
		select: true,
	},
	{
		type: 'Phòng Deluxe Giường Đôi/2 Giường Đơn Nhìn Ra Đại Dương',
		guests: '2 người lớn',
		price: 'VND 4.050.000',
		originalPrice: '',
		discount: '',
		options: [
			'Bao bữa sáng VND 150.000 (không bắt buộc)',
			'Không cần thẻ tín dụng',
			'Miễn phí huỷ trước kỳ nghỉ',
			'Không cần thanh toán trước - thanh toán tại chỗ nghỉ',
			'Genius - Có thể có giảm giá',
		],
		select: true,
	},
	{
		type: 'Phòng Deluxe Giường Đôi/2 Giường Đơn Nhìn Ra Đại Dương',
		guests: '2 người lớn',
		price: 'VND 4.500.000',
		originalPrice: '',
		discount: '',
		options: [
			'Bao bữa sáng tự chọn',
			'Không cần thẻ tín dụng',
			'Miễn phí huỷ trước kỳ nghỉ',
			'Không cần thanh toán trước - thanh toán tại chỗ nghỉ',
			'Genius - Có thể có giảm giá',
		],
		select: true,
	},
	{
		type: 'Phòng Deluxe Giường Đôi/2 Giường Đơn Nhìn Ra Đại Dương',
		guests: '2 người lớn',
		price: 'VND 4.500.000',
		originalPrice: '',
		discount: '',
		options: [
			'Bao bữa sáng VND 150.000 (không bắt buộc)',
			'Không cần thẻ tín dụng',
			'Miễn phí huỷ trước kỳ nghỉ',
			'Không cần thanh toán trước - thanh toán tại chỗ nghỉ',
			'Genius - Có thể có giảm giá',
		],
		select: true,
	},
]
