export default class Constants {
	static optionsStatusBooking = [
		{label: 'Chưa xác nhận', value: 1, color: 'warning'},
		{label: 'Đã xác nhận', value: 2, color: 'primary'},
		{label: 'Đã hoàn thành', value: 3, color: 'success'},
		{label: 'Đã đánh giá', value: 4, color: 'secondary'},
	]
	static vietnamProvinces = [
		{label: 'Hà Nội', value: 1},
		{label: 'Hà Giang', value: 2},
		{label: 'Cao Bằng', value: 3},
		{label: 'Lào Cai', value: 4},
		{label: 'Điện Biên', value: 5},
		{label: 'Lai Châu', value: 6},
		{label: 'Sơn La', value: 7},
		{label: 'Yên Bái', value: 8},
		{label: 'Tuyên Quang', value: 9},
		{label: 'Lạng Sơn', value: 10},
		{label: 'Quảng Ninh', value: 11},
		{label: 'Hòa Bình', value: 12},
		{label: 'Ninh Bình', value: 13},
		{label: 'Thái Bình', value: 14},
		{label: 'Thanh Hóa', value: 15},
		{label: 'Nghệ An', value: 16},
		{label: 'Hà Tĩnh', value: 17},
		{label: 'Quảng Bình', value: 18},
		{label: 'Quảng Trị', value: 19},
		{label: 'Thừa Thiên-Huế', value: 20},
		{label: 'Đà Nẵng', value: 21},
		{label: 'Quảng Nam', value: 22},
		{label: 'Quảng Ngãi', value: 23},
		{label: 'Bình Định', value: 24},
		{label: 'Phú Yên', value: 25},
		{label: 'Khánh Hòa', value: 26},
		{label: 'Ninh Thuận', value: 27},
		{label: 'Bình Thuận', value: 28},
		{label: 'Kon Tum', value: 29},
		{label: 'Gia Lai', value: 30},
		{label: 'Đắk Lắk', value: 31},
		{label: 'Đắk Nông', value: 32},
		{label: 'Lâm Đồng', value: 33},
		{label: 'Bình Phước', value: 34},
		{label: 'Tây Ninh', value: 35},
		{label: 'Bình Dương', value: 36},
		{label: 'Đồng Nai', value: 37},
		{label: 'Bà Rịa-Vũng Tàu', value: 38},
		{label: 'Hồ Chí Minh', value: 39},
		{label: 'Long An', value: 40},
		{label: 'Tiền Giang', value: 41},
		{label: 'Bến Tre', value: 42},
		{label: 'Trà Vinh', value: 43},
		{label: 'Vĩnh Long', value: 44},
		{label: 'Đồng Tháp', value: 45},
		{label: 'An Giang', value: 46},
		{label: 'Kiên Giang', value: 47},
		{label: 'Cần Thơ', value: 48},
		{label: 'Hậu Giang', value: 49},
		{label: 'Sóc Trăng', value: 50},
		{label: 'Bạc Liêu', value: 51},
		{label: 'Cà Mau', value: 52},
		{label: 'Tây Ninh', value: 53},
		{label: 'Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam', value: 54},
		{label: 'Hà Giang', value: 55},
		{label: 'Cao Bằng', value: 56},
		{label: 'Lào Cai', value: 57},
		{label: 'Điện Biên', value: 58},
		{label: 'Lai Châu', value: 59},
		{label: 'Sơn La', value: 60},
		{label: 'Yên Bái', value: 61},
		{label: 'Tuyên Quang', value: 62},
		{label: 'Lạng Sơn', value: 63},
	]
}
export const TYPE_HOST = [
	{
		id: 1,
		name: 'Căn hộ',
	},
	{
		id: 2,
		label: '46-Seater Sleeper Bus',
		name: 'Khách sạn',
	},
	{
		id: 4,
		name: 'Nhà nghỉ',
	},
	{
		id: 5,
		label: '34-Seater Coach',
		name: 'Nhà & căn hộ nguyên căn',
	},

	{
		id: 3,
		name: 'Nhà gỗ',
	},
	{
		id: 6,
		name: 'Biệt thự',
	},
	{
		id: 7,
		label: 'VIP Sleeper Bus',
		name: 'Resort',
	},
	{
		id: 8,
		name: 'Nhà nghỉ B&B',
	},
	{
		id: 9,
		name: 'Xe Du Lịch 30 Chỗ',
	},
	{
		id: 10,
		name: 'Khách sạn tình nhân',
	},
]

export const provinceSearch = [
	{
		id: 21,
		name: 'Đà Nẵng',
	},
	{
		id: 1,
		name: 'Hà Nội',
	},
	{
		id: 2,
		name: 'Vũng Tàu',
	},
	{
		id: 23,
		name: 'Hải Phòng',
	},
	{
		id: 'ho chi minh',
		name: 'TP. Hồ Chí Minh',
	},
]

export const amenitiesSearchConst = [
	{id: '3.1', title: 'Nhìn ra thành phố'},
	{id: '3.2', title: 'Nhìn ra địa danh nổi tiếng'},
	{id: '4.1', title: 'Bàn ghế ngoài trời'},
	{id: '4.3', title: 'Hồ bơi riêng'},
	{id: '8.7', title: 'Minibar'},
	{id: '8.8', title: 'Nhà hàng'},
	{id: '8.9', title: 'Máy pha trà/cà phê'},
	{id: '10.1', title: 'Có chỗ đỗ xe'},
	{
		id: '12.1',
		title: 'Có xuất hóa đơn',
	},
	{id: '13.1', title: 'Dịch vụ đưa đón (Phụ phí)'},
	{id: '13.3', title: 'Chỗ ngủ cho vật nuôi'},
	{
		id: '12.4',
		title: 'Lễ tân 24 giờ',
	},
	{id: '9.1', title: 'Wi-fi miễn phí'},
]

// export const amenitiesConst = [
// 	{
// 		id: '1',
// 		title: 'Phòng tắm',
// 		icon: () => <i className="fas fa-bath"></i>,
// 		items: [
// 			{id: '1.1', title: 'Giấy vệ sinh'},
// 			{id: '1.2', title: 'Khăn tắm'},
// 			{id: '1.3', title: 'Phòng tắm phụ'},
// 			{id: '1.4', title: 'Chậu rửa vệ sinh (bidet)'},
// 			{id: '1.5', title: 'Bồn tắm hoặc Vòi sen'},
// 			{id: '1.6', title: 'Dép'},
// 			{id: '1.7', title: 'Phòng tắm riêng'},
// 			{id: '1.8', title: 'Nhà vệ sinh'},
// 			{id: '1.9', title: 'Đồ vệ sinh cá nhân miễn phí'},
// 			{id: '1.10', title: 'Máy sấy tóc'},
// 			{id: '1.11', title: 'Vòi sen'},
// 		],
// 	},
// 	{
// 		id: '2',
// 		title: 'Phòng ngủ',
// 		icon: () => <i className="fas fe-bed"></i>,
// 		items: [
// 			{id: '2.1', title: 'Ra trải giường'},
// 			{id: '2.2', title: 'Tủ hoặc phòng để quần áo'},
// 		],
// 	},
// 	{
// 		id: '3',
// 		title: 'Tầm nhìn',
// 		icon: () => <i className="fas fa-landmark"></i>,
// 		items: [
// 			{id: '3.1', title: 'Nhìn ra thành phố'},
// 			{id: '3.2', title: 'Nhìn ra địa danh nổi tiếng'},
// 			{id: '3.3', title: 'Tầm nhìn ra khung cảnh'},
// 		],
// 	},
// 	{
// 		id: '4',
// 		title: 'Ngoài trời',
// 		icon: () => <i className="fas fa-seedling"></i>,
// 		items: [
// 			{id: '4.1', title: 'Bàn ghế ngoài trời'},
// 			{id: '4.2', title: 'Sân hiên phơi nắng'},
// 			{id: '4.3', title: 'Hồ bơi riêng'},
// 			{id: '4.4', title: 'Tiện nghi BBQ (Phụ phí)'},
// 			{id: '4.5', title: 'Sân thượng / hiên'},
// 		],
// 	},
// 	{
// 		id: '5',
// 		title: 'Nhà bếp',
// 		icon: () => <i className="fas fa-utensils"></i>,
// 		items: [
// 			{id: '5.1', title: 'Ấm đun nước điện'},
// 			{id: '5.2', title: 'Tủ lạnh'},
// 		],
// 	},
// 	{
// 		id: '6',
// 		title: 'Khu vực phòng khách',
// 		icon: () => <i className="fas fa-home"></i>,
// 		items: [
// 			{id: '6.1', title: 'Lò sưởi'},
// 			{id: '6.2', title: 'Khu vực tiếp khách'},
// 			{id: '6.3', title: 'Bàn làm việc'},
// 		],
// 	},
// 	{
// 		id: '7',
// 		title: 'Truyền thông & Công nghệ',
// 		icon: () => <i className="fas fa-television"></i>,
// 		items: [
// 			{id: '7.1', title: 'TV màn hình phẳng'},
// 			{id: '7.2', title: 'Truyền hình cáp'},
// 			{id: '7.3', title: 'Truyền hình vệ tinh'},
// 			{id: '7.4', title: 'Điện thoại'},
// 			{id: '7.5', title: 'TV'},
// 		],
// 	},
// 	{
// 		id: '8',
// 		title: 'Đồ ăn & thức uống',
// 		icon: () => <i className="fas fa-cutlery"></i>,
// 		items: [
// 			{id: '8.1', title: 'Trái cây (Phụ phí)'},
// 			{id: '8.2', title: 'Rượu vang/sâm panh (Phụ phí)'},
// 			{id: '8.3', title: 'Bữa ăn tự chọn phù hợp với trẻ em'},
// 			{id: '8.4', title: 'Bữa ăn trẻ em (Phụ phí)'},
// 			{id: '8.5', title: 'Thực đơn ăn kiêng đặc biệt (theo yêu cầu)'},
// 			{id: '8.6', title: 'Bữa sáng tại phòng'},
// 			{id: '8.7', title: 'Minibar'},
// 			{id: '8.8', title: 'Nhà hàng'},
// 			{id: '8.9', title: 'Máy pha trà/cà phê'},
// 		],
// 	},
// 	{
// 		id: '9',
// 		title: 'Internet',
// 		icon: () => <i className="fas fa-wifi"></i>,
// 		items: [{id: '9.1', title: 'Wi-fi miễn phí'}],
// 	},
// 	{
// 		id: '10',
// 		title: 'Chỗ đậu xe',
// 		icon: () => <i className="fas fa-product-hunt"></i>,
// 		items: [{id: '10.1', title: 'Có chỗ đỗ xe'}],
// 	},
// 	{
// 		id: '11',
// 		title: 'Phương tiện đi lại',
// 		icon: () => <i className="fas fa-car"></i>,
// 		items: [{id: '11.1', title: 'Vé đi phương tiện công cộng (Phụ phí)'}],
// 	},
// 	{
// 		id: '12',
// 		title: 'Dịch vụ lễ tân',
// 		icon: () => <i className="fas fa-wifi"></i>,
// 		items: [
// 			{
// 				id: '12.1',
// 				title: 'Có xuất hóa đơn',
// 			},
// 			{
// 				id: '12.2',
// 				title: 'Tủ khóa',
// 			},
// 			{
// 				id: '12.3',
// 				title: 'Thu đổi ngoại tệ',
// 			},
// 			{
// 				id: '12.4',
// 				title: 'Lễ tân 24 giờ',
// 			},
// 			{
// 				id: '12.5',
// 				title: 'Giữ hành lín',
// 			},
// 		],
// 	},
// 	{
// 		id: '13',
// 		title: 'Tổng quát',
// 		icon: () => <i className="fas fa-info-circle"></i>,
// 		items: [
// 			{id: '13.1', title: 'Dịch vụ đưa đón (Phụ phí)'},
// 			{id: '13.2', title: 'Bát ăn cho vật nuôi'},
// 			{id: '13.3', title: 'Chỗ ngủ cho vật nuôi'},
// 			{id: '13.4', title: 'Giao nhận đồ tạp hóa (Phụ phí)'},
// 			{id: '13.5', title: 'Khu vực xem TV/sành chung'},
// 			{id: '13.6', title: 'Không gây dị ứng'},
// 			{id: '13.7', title: 'Khu vực cho phép hút thuốc'},
// 			{id: '13.8', title: 'Điều hòa nhiệt độ'},
// 			{id: '13.9', title: 'Phòng không gây dị ứng'},
// 			{id: '13.10', title: 'Màn chống muỗi'},
// 		],
// 	},
// 	{
// 		id: '14',
// 		title: 'Thanh toán',
// 		icon: () => <i className="fas fa-atm"></i>,
// 		items: [
// 			{id: '14.1', title: 'Không cần thanh toán trước'},
// 			{id: '14.2', title: 'Thanh toán qua MOMO'},
// 		],
// 	},
// ]
